spring.application.name=fraude-api
spring.datasource.url=jdbc:postgresql://localhost:5432/fraude_db
spring.datasource.username=postgres
spring.datasource.password=2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true